server:
  port: 80

eureka: #eureka实例定义
  client:
    register-with-eureka: false # false：不向注册中心注册自己
    service-url:  #客户端进行Eureka注册的配置
      defaultZone: http://edmin:mldnjava@192.168.2.176:7001/eureka/,http://edmin:mldnjava@192.168.2.176:7002/eureka/,http://edmin:mldnjava@192.168.2.176:7003/eureka/
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json #可以被压缩的类型
      min-request-size: 2048  #超过2048字节进行压缩
  hystrix:  #Feign启用Hystrix熔断机制
    enabled: true

logging:  #开启feign的相关日志信息
  level:
    com:
      bjsxt:
        service: debug
