server:
  port: 9101

eureka: #客户端进行Eureka注册的配置
  client:
    register-with-eureka: false # false：不向注册中心注册自己
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka/,http://edmin:mldnjava@eureka-7002.com:7002/eureka/,http://edmin:mldnjava@eureka-7003.com:7003/eureka/


turbine:
  app-config: MICROCLOUD-PROVIDER-DEPT  #定义所要监控的微服务信息
  cluster-name-expression: new String("default")  #设置一个监控的表达式，通过此表达式表示要获取的监控信息名称
  instanceUrlSuffix: /hystrix.stream
  combine-host-port: true