server:
  port: 7101

spring:
  application:
    name: microcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:WHCSX/springcloud-demo_config.git
    bus:
      enabled: true #启用bus总线
  rabbitmq: #现在将集成RabbitMQ作为消息服务总线处理
    host: 192.168.2.156 #RabbitMQ主机服务地址
    port: 5672  #RabbitMQ的监听端口
    username: mldnjava  #用户名
    password: hello #密码
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

encrypt:
  key: mldnjava.cn  #设置了一个加密的访问密钥

eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@192.168.2.176:7001/eureka/,http://edmin:mldnjava@192.168.2.176:7002/eureka/,http://edmin:mldnjava@192.168.2.176:7003/eureka/
  instance:
    prefer-ip-address: true #在地址栏上使用IP地址进行显示
    instance-id: config-7101.com  #在信息列表时显示主机名称